- name: Query for a default workspace
  azure_rm_loganalyticsworkspace_facts:
      resource_group: "{{ resource_group }}"
  register: __workspaces

- name: Create a new workspace
  azure_rm_loganalyticsworkspace:
      name: "{{ name }}{{ __rsfx }}"
      resource_group: "{{ resource_group }}"
  register: __workspace_instance
  when: __workspaces.workspaces | length == 0

- name: Save workspace id
  set_fact:
      workspace_resource_id: "{{ __workspace_instance.id }}"
  when: __workspace_instance is defined and 'id' in __workspace_instance

- name: Using the default workspace {{ __workspaces.workspaces[0].name }}
  set_fact:
      workspace_resource_id: "{{ __workspaces.workspaces[0].id }}"
  when: __workspaces.workspaces | length > 0
