- name: Ensure resource group exist
  azure_rm_resourcegroup_facts:
      name: "{{ resource_group }}"
  register: __rg

- name: Create resource group
  azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  when: __rg.ansible_facts.azure_resourcegroups | length == 0
